a="Hello World"
operation1=a.upper()
operation2=a.lower()
operation3=a.rstrip("d")
operation4=a.lstrip("H")
operation5=a.replace(" ","beautiful")
operation6=a.split()
operation7=a.capitalize()
operation8=a.center(30,"*")
operation9=a.swapcase()
operation10=a.endswith("d")
operation11=a.isalnum()
print(" ",operation1)
print(" ",operation2)
print(" ",operation3)
print(" ",operation4)
print(" ",operation5)
print(" ",operation6)
print(" ",operation7)
print(" ",operation8)
print(" ",operation9)
print(" ",operation10)
print(" ",operation11)